FROM node:12-alpine

WORKDIR /usr/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY src ./src

COPY nest-cli.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY modules.d.ts ./
COPY policy.conf ./
COPY ./jwt ./jwt

ENTRYPOINT [ "yarn" ]
CMD [ "start:debug" ]
